/*
 * Copyright (C) 2012 cismet GmbH
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package de.cismet.verdis.gui;

import com.jgoodies.looks.plastic.Plastic3DLookAndFeel;
import de.cismet.tools.gui.log4jquickconfig.Log4JQuickConfig;
import java.util.Calendar;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;
import org.openide.util.Exceptions;

/**
 *
 * @author jruiz
 */
public class FortfuehrungsanlaesseDialog extends javax.swing.JDialog {
    
    private static Logger LOG = Logger.getLogger(FortfuehrungsanlaesseDialog.class);

    /**
     * Creates new form FortfuehrungsanlaesseDialog
     */
    public FortfuehrungsanlaesseDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();        
        
        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {

        // If cell selection is enabled, both row and column change events are fired
                if (e.getSource() == jTable1.getSelectionModel() && jTable1.getRowSelectionAllowed()) {
                    int first = e.getFirstIndex();
                    int last = e.getLastIndex();
                    fortfuehrungsTableListSelectionChanged(e);
                }

            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        panPeriod = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jXDatePicker2 = new org.jdesktop.swingx.JXDatePicker();
        jPanel2 = new javax.swing.JPanel();
        btnThisWeek = new javax.swing.JToggleButton();
        btnLastWeek = new javax.swing.JToggleButton();
        btnThisMonth = new javax.swing.JToggleButton();
        btnLastMonth = new javax.swing.JToggleButton();
        jPanel7 = new javax.swing.JPanel();
        panMasterDetail = new javax.swing.JPanel();
        panMaster = new javax.swing.JPanel();
        btnRefreshAnlaesse = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panDetail = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        labDokumentLink = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstKassenzeichen = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btnCloseDialog = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(FortfuehrungsanlaesseDialog.class, "FortfuehrungsanlaesseDialog.title")); // NOI18N
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        panPeriod.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(FortfuehrungsanlaesseDialog.class, "FortfuehrungsanlaesseDialog.panPeriod.border.title"))); // NOI18N
        panPeriod.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText(org.openide.util.NbBundle.getMessage(FortfuehrungsanlaesseDialog.class, "FortfuehrungsanlaesseDialog.jLabel1.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        panPeriod.add(jLabel1, gridBagConstraints);

        jLabel2.setText(org.openide.util.NbBundle.getMessage(FortfuehrungsanlaesseDialog.class, "FortfuehrungsanlaesseDialog.jLabel2.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        panPeriod.add(jLabel2, gridBagConstraints);

        jXDatePicker1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jXDatePicker1PropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        panPeriod.add(jXDatePicker1, gridBagConstraints);

        jXDatePicker2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jXDatePicker2PropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panPeriod.add(jXDatePicker2, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridLayout(2, 3, 5, 5));

        buttonGroup1.add(btnThisWeek);
        btnThisWeek.setText(org.openide.util.NbBundle.getMessage(FortfuehrungsanlaesseDialog.class, "FortfuehrungsanlaesseDialog.btnThisWeek.text")); // NOI18N
        btnThisWeek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThisWeekActionPerformed(evt);
            }
        });
        jPanel2.add(btnThisWeek);

        buttonGroup1.add(btnLastWeek);
        btnLastWeek.setText(org.openide.util.NbBundle.getMessage(FortfuehrungsanlaesseDialog.class, "FortfuehrungsanlaesseDialog.btnLastWeek.text")); // NOI18N
        btnLastWeek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastWeekActionPerformed(evt);
            }
        });
        jPanel2.add(btnLastWeek);

        buttonGroup1.add(btnThisMonth);
        btnThisMonth.setText(org.openide.util.NbBundle.getMessage(FortfuehrungsanlaesseDialog.class, "FortfuehrungsanlaesseDialog.btnThisMonth.text")); // NOI18N
        btnThisMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThisMonthActionPerformed(evt);
            }
        });
        jPanel2.add(btnThisMonth);

        buttonGroup1.add(btnLastMonth);
        btnLastMonth.setText(org.openide.util.NbBundle.getMessage(FortfuehrungsanlaesseDialog.class, "FortfuehrungsanlaesseDialog.btnLastMonth.text")); // NOI18N
        btnLastMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastMonthActionPerformed(evt);
            }
        });
        jPanel2.add(btnLastMonth);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        panPeriod.add(jPanel2, gridBagConstraints);

        jPanel7.setPreferredSize(new java.awt.Dimension(50, 10));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.weightx = 1.0;
        panPeriod.add(jPanel7, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(panPeriod, gridBagConstraints);

        panMasterDetail.setLayout(new java.awt.GridBagLayout());

        panMaster.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(FortfuehrungsanlaesseDialog.class, "FortfuehrungsanlaesseDialog.panMaster.border.title"))); // NOI18N
        panMaster.setLayout(new java.awt.GridBagLayout());

        btnRefreshAnlaesse.setText(org.openide.util.NbBundle.getMessage(FortfuehrungsanlaesseDialog.class, "FortfuehrungsanlaesseDialog.btnRefreshAnlaesse.text")); // NOI18N
        btnRefreshAnlaesse.setEnabled(false);
        btnRefreshAnlaesse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshAnlaesseActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        panMaster.add(btnRefreshAnlaesse, gridBagConstraints);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Datum", "Name", "Typ", "Beschreibung"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        panMaster.add(jScrollPane3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        panMasterDetail.add(panMaster, gridBagConstraints);

        panDetail.setBorder(null);
        panDetail.setMinimumSize(new java.awt.Dimension(250, 137));
        panDetail.setPreferredSize(new java.awt.Dimension(250, 244));
        panDetail.setVerifyInputWhenFocusTarget(false);
        panDetail.setLayout(new java.awt.GridBagLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(FortfuehrungsanlaesseDialog.class, "FortfuehrungsanlaesseDialog.jPanel3.border.title"))); // NOI18N
        jPanel3.setLayout(new java.awt.GridBagLayout());

        labDokumentLink.setText(org.openide.util.NbBundle.getMessage(FortfuehrungsanlaesseDialog.class, "FortfuehrungsanlaesseDialog.labDokumentLink.text")); // NOI18N
        labDokumentLink.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel3.add(labDokumentLink, gridBagConstraints);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel3.add(jPanel5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panDetail.add(jPanel3, gridBagConstraints);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(FortfuehrungsanlaesseDialog.class, "FortfuehrungsanlaesseDialog.jPanel4.border.title"))); // NOI18N
        jPanel4.setLayout(new java.awt.GridBagLayout());

        lstKassenzeichen.setModel(new DefaultListModel());
        lstKassenzeichen.setEnabled(false);
        lstKassenzeichen.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstKassenzeichenValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstKassenzeichen);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel4.add(jScrollPane2, gridBagConstraints);

        jButton1.setText(org.openide.util.NbBundle.getMessage(FortfuehrungsanlaesseDialog.class, "FortfuehrungsanlaesseDialog.jButton1.text")); // NOI18N
        jButton1.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        jPanel4.add(jButton1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        panDetail.add(jPanel4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        panMasterDetail.add(panDetail, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(panMasterDetail, gridBagConstraints);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel1.add(jPanel6, gridBagConstraints);

        btnCloseDialog.setText(org.openide.util.NbBundle.getMessage(FortfuehrungsanlaesseDialog.class, "FortfuehrungsanlaesseDialog.btnCloseDialog.text")); // NOI18N
        btnCloseDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseDialogActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(btnCloseDialog, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshAnlaesseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshAnlaesseActionPerformed
        refreshFortfuehrungsList();
    }//GEN-LAST:event_btnRefreshAnlaesseActionPerformed

    private void btnThisWeekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThisWeekActionPerformed
        final Calendar calendar = Calendar.getInstance();
        
        final Date toDate = calendar.getTime();
        
        calendar.set(Calendar.DAY_OF_WEEK, Calendar.MONDAY);
        final Date fromDate = calendar.getTime();
        
        jXDatePicker1.setDate(fromDate);
        jXDatePicker2.setDate(toDate);
        
        periodChanged();
    }//GEN-LAST:event_btnThisWeekActionPerformed

    private void btnLastWeekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastWeekActionPerformed
        final Calendar calendar = Calendar.getInstance();
        
        calendar.set(Calendar.DAY_OF_WEEK, Calendar.MONDAY);
        final Date toDate = calendar.getTime();
        
        calendar.add(Calendar.DATE, -7);
        final Date fromDate = calendar.getTime();
        
        jXDatePicker1.setDate(fromDate);
        jXDatePicker2.setDate(toDate);
        
        periodChanged();
    }//GEN-LAST:event_btnLastWeekActionPerformed

    private void btnThisMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThisMonthActionPerformed
        final Calendar calendar = Calendar.getInstance();
        
        final Date toDate = calendar.getTime();
        
        calendar.set(Calendar.DAY_OF_MONTH, 1);        
        final Date fromDate = calendar.getTime();
        
        jXDatePicker1.setDate(fromDate);
        jXDatePicker2.setDate(toDate);
        
        periodChanged();
    }//GEN-LAST:event_btnThisMonthActionPerformed

    private void btnLastMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastMonthActionPerformed
        final Calendar calendar = Calendar.getInstance();
        
        calendar.set(Calendar.DAY_OF_MONTH, 1);
        final Date toDate = calendar.getTime();
        
        calendar.add(Calendar.MONTH, -1);        
        final Date fromDate = calendar.getTime();
        
        jXDatePicker1.setDate(fromDate);
        jXDatePicker2.setDate(toDate);
        
        periodChanged();
    }//GEN-LAST:event_btnLastMonthActionPerformed

    private void jXDatePicker1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jXDatePicker1PropertyChange
        manualPeriodChangePerformed();
    }//GEN-LAST:event_jXDatePicker1PropertyChange

    private void jXDatePicker2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jXDatePicker2PropertyChange
        manualPeriodChangePerformed();
    }//GEN-LAST:event_jXDatePicker2PropertyChange

    private void btnCloseDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseDialogActionPerformed
        dispose();
    }//GEN-LAST:event_btnCloseDialogActionPerformed

    private void lstKassenzeichenValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstKassenzeichenValueChanged
        jButton1.setEnabled(!lstKassenzeichen.getSelectionModel().isSelectionEmpty());
    }//GEN-LAST:event_lstKassenzeichenValueChanged

    private void refreshKassenzeichenList() {
        ((DefaultListModel) lstKassenzeichen.getModel()).removeAllElements();
        final int selectedRow = jTable1.getSelectedRow() + 1;

        if (selectedRow > 0 && selectedRow <= jTable1.getRowCount()) {
            labDokumentLink.setText("<html><a href=\"http://server/ffax.pdf\">fortfuehrungsanlass_" + selectedRow + ".pdf</a>");         
            setDetailEnabled(true);
        } else {
            labDokumentLink.setText("");
            setDetailEnabled(false);
        }
        
        switch (selectedRow) {
            case 1: {
                ((DefaultListModel) lstKassenzeichen.getModel()).addElement("61004629");
                ((DefaultListModel) lstKassenzeichen.getModel()).addElement("61004729");
                ((DefaultListModel) lstKassenzeichen.getModel()).addElement("61004829");
                ((DefaultListModel) lstKassenzeichen.getModel()).addElement("61004929");
            }
            break;
            case 2: {
                ((DefaultListModel) lstKassenzeichen.getModel()).addElement("62004329");
                ((DefaultListModel) lstKassenzeichen.getModel()).addElement("62004429");
                ((DefaultListModel) lstKassenzeichen.getModel()).addElement("62004529");
                ((DefaultListModel) lstKassenzeichen.getModel()).addElement("62004629");
                ((DefaultListModel) lstKassenzeichen.getModel()).addElement("62004729");
                ((DefaultListModel) lstKassenzeichen.getModel()).addElement("62004829");
                ((DefaultListModel) lstKassenzeichen.getModel()).addElement("62004929");
            }
            break;
            case 3: {
                ((DefaultListModel) lstKassenzeichen.getModel()).addElement("63004129");
                ((DefaultListModel) lstKassenzeichen.getModel()).addElement("63004229");
            }
            break;
            case 4: {
                ((DefaultListModel) lstKassenzeichen.getModel()).addElement("64004429");
                ((DefaultListModel) lstKassenzeichen.getModel()).addElement("64004529");
                ((DefaultListModel) lstKassenzeichen.getModel()).addElement("64004829");
                ((DefaultListModel) lstKassenzeichen.getModel()).addElement("64004929");
            }
            break;
            case 5: {
                ((DefaultListModel) lstKassenzeichen.getModel()).addElement("65004129");
                ((DefaultListModel) lstKassenzeichen.getModel()).addElement("65004229");
            }
            break;
            case 6: {
                ((DefaultListModel) lstKassenzeichen.getModel()).addElement("66004629");
                ((DefaultListModel) lstKassenzeichen.getModel()).addElement("66004729");
                ((DefaultListModel) lstKassenzeichen.getModel()).addElement("66004929");
            }
            break;
            case 7: {
                ((DefaultListModel) lstKassenzeichen.getModel()).addElement("67004529");
                ((DefaultListModel) lstKassenzeichen.getModel()).addElement("67004729");
            }
            break;
            case 8: {
                ((DefaultListModel) lstKassenzeichen.getModel()).addElement("68004129");
                ((DefaultListModel) lstKassenzeichen.getModel()).addElement("68004229");
                ((DefaultListModel) lstKassenzeichen.getModel()).addElement("68004329");
                ((DefaultListModel) lstKassenzeichen.getModel()).addElement("68004429");
                ((DefaultListModel) lstKassenzeichen.getModel()).addElement("68004529");
                ((DefaultListModel) lstKassenzeichen.getModel()).addElement("68004629");
            } break;
        }
    }
    
    private void manualPeriodChangePerformed() {
        buttonGroup1.clearSelection();
        periodChanged();
    }
    
    private void fortfuehrungsTableListSelectionChanged(ListSelectionEvent e) {
        refreshKassenzeichenList();
    }
    
    private void periodChanged() {
        final boolean anlaesseEnabled = jXDatePicker1.getDate() != null && jXDatePicker2.getDate() != null;
        btnRefreshAnlaesse.setEnabled(anlaesseEnabled);
        jTable1.setEnabled(anlaesseEnabled);
    }    
    
    private void refreshFortfuehrungsList() {
        jTable1.getSelectionModel().clearSelection();
        ((DefaultTableModel) jTable1.getModel()).getDataVector().clear();
        
        ((DefaultTableModel) jTable1.getModel()).addRow(new Object[] { "01.01.1970", "Fortführungsanlass 1", "", "Beschreibung 1" });
        ((DefaultTableModel) jTable1.getModel()).addRow(new Object[] { "01.01.1970", "Fortführungsanlass 2", "", "Beschreibung 2" });
        ((DefaultTableModel) jTable1.getModel()).addRow(new Object[] { "01.01.1970", "Fortführungsanlass 3", "", "Beschreibung 3" });
        ((DefaultTableModel) jTable1.getModel()).addRow(new Object[] { "01.01.1970", "Fortführungsanlass 4", "", "Beschreibung 4" });
        ((DefaultTableModel) jTable1.getModel()).addRow(new Object[] { "01.01.1970", "Fortführungsanlass 5", "", "Beschreibung 5" });
        ((DefaultTableModel) jTable1.getModel()).addRow(new Object[] { "01.01.1970", "Fortführungsanlass 6", "", "Beschreibung 6" });
        ((DefaultTableModel) jTable1.getModel()).addRow(new Object[] { "01.01.1970", "Fortführungsanlass 7", "", "Beschreibung 7" });
        ((DefaultTableModel) jTable1.getModel()).addRow(new Object[] { "01.01.1970", "Fortführungsanlass 8", "", "Beschreibung 8" });
    }
    
    private void setDetailEnabled(final boolean enabled) {
        lstKassenzeichen.setEnabled(enabled);
        labDokumentLink.setEnabled(enabled);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FortfuehrungsanlaesseDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FortfuehrungsanlaesseDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FortfuehrungsanlaesseDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FortfuehrungsanlaesseDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                try {
                    javax.swing.UIManager.setLookAndFeel(new Plastic3DLookAndFeel());
                    Log4JQuickConfig.configure4LumbermillOnLocalhost();                    
                } catch (UnsupportedLookAndFeelException ex) {
                    Exceptions.printStackTrace(ex);
                }
                
                FortfuehrungsanlaesseDialog dialog = new FortfuehrungsanlaesseDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCloseDialog;
    private javax.swing.JToggleButton btnLastMonth;
    private javax.swing.JToggleButton btnLastWeek;
    private javax.swing.JButton btnRefreshAnlaesse;
    private javax.swing.JToggleButton btnThisMonth;
    private javax.swing.JToggleButton btnThisWeek;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker2;
    private javax.swing.JLabel labDokumentLink;
    private javax.swing.JList lstKassenzeichen;
    private javax.swing.JPanel panDetail;
    private javax.swing.JPanel panMaster;
    private javax.swing.JPanel panMasterDetail;
    private javax.swing.JPanel panPeriod;
    // End of variables declaration//GEN-END:variables
}
