/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
package de.cismet.verdis.gui;

/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/

import Sirius.server.middleware.types.MetaObject;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

import de.cismet.tools.gui.StaticSwingTools;

import de.cismet.verdis.CidsAppBackend;

/*
 * Copyright (C) 2014 cismet GmbH
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * DOCUMENT ME!
 *
 * @author   jruiz
 * @version  $Revision$, $Date$
 */
public class GrundbuchblattSucheDialog extends javax.swing.JDialog {

    //~ Static fields/initializers ---------------------------------------------

    private static final transient org.apache.log4j.Logger LOG = org.apache.log4j.Logger.getLogger(
            GrundbuchblattSucheDialog.class);

    private static GrundbuchblattSucheDialog INSTANCE;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private de.cismet.cids.custom.wupp.client.alkis.GrundbuchblattInputField grundbuchblattInputField1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form GrundbuchungsblattKassenzeichenSucheDialog.
     */
    private GrundbuchblattSucheDialog() {
        super((JFrame)null, false);
        initComponents();
        getRootPane().setDefaultButton(jButton1);
        jProgressBar1.setVisible(false);
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    public static GrundbuchblattSucheDialog getInstance() {
        if (INSTANCE == null) {
            INSTANCE = new GrundbuchblattSucheDialog();
        }
        return INSTANCE;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        grundbuchblattInputField1 = new de.cismet.cids.custom.wupp.client.alkis.GrundbuchblattInputField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();

        setTitle("Suche über Grundbuchblattnummer");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(grundbuchblattInputField1, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jButton1, "Kassenzeichen suchen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {

                @Override
                public void actionPerformed(final java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jButton1, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(
            jLabel1,
            "<html>Geben Sie eine Grundbuchblattnummer ein,<br/>um nach Kassenzeichen zu suchen.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabel1, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(
            jLabel2,
            org.openide.util.NbBundle.getMessage(
                GrundbuchblattSucheDialog.class,
                "GrundbuchblattSucheDialog.jLabel2.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabel2, gridBagConstraints);

        jProgressBar1.setIndeterminate(true);
        jProgressBar1.setString(org.openide.util.NbBundle.getMessage(
                GrundbuchblattSucheDialog.class,
                "GrundbuchblattSucheDialog.jProgressBar1.string")); // NOI18N
        jProgressBar1.setStringPainted(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        jPanel1.add(jProgressBar1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    } // </editor-fold>//GEN-END:initComponents

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void jButton1ActionPerformed(final java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton1ActionPerformed
        grundbuchblattInputField1.finish();
        new SwingWorker<MetaObject[], Void>() {

                @Override
                protected MetaObject[] doInBackground() throws Exception {
                    final String grundbuchblattnummer = grundbuchblattInputField1.getGrundbuchblattnummer();
                    final String grundbuchblattnummerExt = (grundbuchblattnummer.length() == 14)
                        ? grundbuchblattnummer : (grundbuchblattnummer + " ");
                    jProgressBar1.setVisible(true);
                    jButton1.setVisible(false);
                    return CidsAppBackend.getInstance()
                                .getMetaObject(
                                    "SELECT (SELECT id FROM cs_class WHERE table_name ILIKE 'alkis_buchungsblatt') AS class_id, id AS object_id FROM alkis_buchungsblatt WHERE buchungsblattcode ILIKE '"
                                    + grundbuchblattnummerExt
                                    + "';",
                                    "WUNDA_BLAU");
                }

                @Override
                protected void done() {
                    MetaObject[] grundbuchblaetter = null;
                    try {
                        grundbuchblaetter = get();
                    } catch (final Exception ex) {
                        LOG.error(ex, ex);
                    } finally {
                        jProgressBar1.setVisible(false);
                        jButton1.setVisible(true);
                    }

                    if ((grundbuchblaetter != null) && (grundbuchblaetter.length > 0)) {
                        setVisible(false);
                        KassenzeichenGrundbuchblattSearchDialog.getInstance().setGrundbuchblatt(grundbuchblaetter[0]);
                        StaticSwingTools.showDialog(KassenzeichenGrundbuchblattSearchDialog.getInstance());
                    } else {
                        JOptionPane.showMessageDialog(
                            GrundbuchblattSucheDialog.this,
                            "Das Buchungsblatt wurde nicht gefunden.",
                            "Suche",
                            JOptionPane.INFORMATION_MESSAGE);
                    }
                }
            }.execute();
    } //GEN-LAST:event_jButton1ActionPerformed
}
