/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
package de.cismet.verdis.gui;

/**
 * DOCUMENT ME!
 *
 * @author   jruiz
 * @version  $Revision$, $Date$
 */
public class LockingDialog extends javax.swing.JDialog {

    //~ Static fields/initializers ---------------------------------------------

    private static LockingDialog INSTANCE;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form LockingDialog.
     */
    private LockingDialog() {
        super();
        initComponents();
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(LockingDialog.class, "LockingDialog.title")); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jProgressBar1.setIndeterminate(true);
        jProgressBar1.setMaximumSize(new java.awt.Dimension(300, 22));
        jProgressBar1.setMinimumSize(new java.awt.Dimension(300, 22));
        jProgressBar1.setPreferredSize(new java.awt.Dimension(300, 22));
        jProgressBar1.setString(org.openide.util.NbBundle.getMessage(
                LockingDialog.class,
                "LockingDialog.jProgressBar1.string")); // NOI18N
        jProgressBar1.setStringPainted(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(jProgressBar1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    } // </editor-fold>//GEN-END:initComponents

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    public static LockingDialog getInstance() {
        if (INSTANCE == null) {
            INSTANCE = new LockingDialog();
            INSTANCE.setModal(true);
        }
        return INSTANCE;
    }
    /**
     * DOCUMENT ME!
     */
    public void reset() {
        jProgressBar1.setString("Querverweise werden abgerufen...");
        jProgressBar1.setMaximum(0);
        jProgressBar1.setIndeterminate(true);
    }

    /**
     * DOCUMENT ME!
     */
    public void check() {
        jProgressBar1.setString("vorhandene Sperre werden geprüft...");
        jProgressBar1.setMaximum(0);
        jProgressBar1.setIndeterminate(true);
    }

    /**
     * DOCUMENT ME!
     *
     * @param  max  DOCUMENT ME!
     */
    public void setMaxProgress(final int max) {
        jProgressBar1.setString("Kassenzeichen werden gesperrt...");
        jProgressBar1.setMaximum(max);
        jProgressBar1.setIndeterminate(false);
    }

    /**
     * DOCUMENT ME!
     *
     * @param  prog  DOCUMENT ME!
     */
    public void setProgress(final int prog) {
        jProgressBar1.setValue(prog);
    }
}
