/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
/*
 * SummenPanel.java
 *
 * Created on 5. Januar 2005, 14:01
 */
package de.cismet.verdis.gui;

import java.awt.Color;

import de.cismet.cids.dynamics.CidsBean;
import de.cismet.cids.dynamics.CidsBeanStore;

/**
 * DOCUMENT ME!
 *
 * @author   hell
 * @version  $Revision$, $Date$
 */
public class RegenFlaechenSummenPanel extends javax.swing.JPanel implements CidsBeanStore {

    //~ Static fields/initializers ---------------------------------------------

    private static final org.apache.log4j.Logger LOG = org.apache.log4j.Logger.getLogger(
            RegenFlaechenSummenPanel.class);

    //~ Instance fields --------------------------------------------------------

    private RegenFlaechenSummenTableModel tableModel;
    private CidsBean kassenzeichenBean;
//    private Connection connection;
//    private boolean busy = false;
//    private ImageIcon ic_default;
//    private ImageIcon ic_0;
//    private ImageIcon ic_1;
//    private ImageIcon ic_2;
//    private ImageIcon ic_3;
//    private ImageIcon ic_4;
//    private ImageIcon ic_5;
//    private ImageIcon ic_6;
//    private ImageIcon ic_7;
//    // PERHAPS BETTER TO GIVE THE SUMMENPANEL THE VIEWOBJECT
//    private Main main;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panTab;
    private javax.swing.JTable tabSum;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form SummenPanel.
     */
    public RegenFlaechenSummenPanel() {
//        ic_default = new javax.swing.ImageIcon(getClass().getResource(
//                "/de/cismet/verdis/res/images/titlebars/sum.png"));
//        ic_0 = new javax.swing.ImageIcon(getClass().getResource(
//                "/de/cismet/verdis/res/images/titlebars/animation/sum_0.png"));
//        ic_1 = new javax.swing.ImageIcon(getClass().getResource(
//                "/de/cismet/verdis/res/images/titlebars/animation/sum_1.png"));
//        ic_2 = new javax.swing.ImageIcon(getClass().getResource(
//                "/de/cismet/verdis/res/images/titlebars/animation/sum_2.png"));
//        ic_3 = new javax.swing.ImageIcon(getClass().getResource(
//                "/de/cismet/verdis/res/images/titlebars/animation/sum_3.png"));
//        ic_4 = new javax.swing.ImageIcon(getClass().getResource(
//                "/de/cismet/verdis/res/images/titlebars/animation/sum_4.png"));
//        ic_5 = new javax.swing.ImageIcon(getClass().getResource(
//                "/de/cismet/verdis/res/images/titlebars/animation/sum_5.png"));
//        ic_6 = new javax.swing.ImageIcon(getClass().getResource(
//                "/de/cismet/verdis/res/images/titlebars/animation/sum_6.png"));
//        ic_7 = new javax.swing.ImageIcon(getClass().getResource(
//                "/de/cismet/verdis/res/images/titlebars/animation/sum_7.png"));
        initComponents();
        tableModel = new RegenFlaechenSummenTableModel();
        tabSum.setModel(tableModel);
        tabSum.setDefaultRenderer(Object.class, new RegenFlaechenSummenTableCellRenderer());
        // tabSum.getColumnModel().getColumn(0).setPreferredWidth(10);
        // tabSum.setTableHeader(null);
        // tabSum.getColumnModel().getColumn(0).setMaxWidth(40);
        // tabSum.getColumnModel().getColumn(1).setMaxWidth(40);
        // tabSum.getColumnModel().getColumn(2).setMaxWidth(20);
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * Inserting Docking Window functionalty (Sebastian) 24.07.07 temporary disabled --> handled in Main.java.
     *
     * @param  c  DOCUMENT ME!
     */
    public void setLeftTitlebarColor(final Color c) {
        // panTitle.setLeftColor(c);
        // panTitle.repaint();
    }

    @Override
    public CidsBean getCidsBean() {
        return kassenzeichenBean;
    }

    @Override
    public void setCidsBean(final CidsBean cidsBean) {
        kassenzeichenBean = cidsBean;
        tableModel.setCidsBean(cidsBean);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        panTab = new javax.swing.JPanel();
        tabSum = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        panTab.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        panTab.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        panTab.setMinimumSize(new java.awt.Dimension(100, 84));
        panTab.setPreferredSize(new java.awt.Dimension(120, 84));
        panTab.setLayout(new java.awt.BorderLayout());

        tabSum.setBackground(javax.swing.UIManager.getDefaults().getColor("Label.background"));
        tabSum.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                    { null, null, null, null },
                    { null, null, null, null },
                    { null, null, null, null },
                    { null, null, null, null }
                },
                new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
        tabSum.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabSum.setFocusable(false);
        tabSum.setRowSelectionAllowed(false);
        tabSum.setShowHorizontalLines(false);
        tabSum.setShowVerticalLines(false);
        panTab.add(tabSum, java.awt.BorderLayout.CENTER);

        add(panTab, java.awt.BorderLayout.CENTER);
    } // </editor-fold>//GEN-END:initComponents
}
