/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
package de.cismet.verdis.gui.befreiungerlaubnis;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import javax.swing.JDialog;

import de.cismet.cids.dynamics.CidsBean;

import de.cismet.tools.gui.StaticSwingTools;

import de.cismet.verdis.CidsAppBackend;

import de.cismet.verdis.gui.AbstractCidsBeanTable;
import de.cismet.verdis.gui.AbstractCidsBeanTablePanel;

/**
 * DOCUMENT ME!
 *
 * @author   jruiz
 * @version  $Revision$, $Date$
 */
public class BefreiungerlaubnisTablePanel extends AbstractCidsBeanTablePanel {

    //~ Static fields/initializers ---------------------------------------------

    private static final org.apache.log4j.Logger LOG = org.apache.log4j.Logger.getLogger(
            BefreiungerlaubnisTablePanel.class);

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private de.cismet.verdis.gui.befreiungerlaubnis.BefreiungerlaubnisTable befreiungerlaubnisTable1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form RegenflaechenTabellenPanel.
     */
    public BefreiungerlaubnisTablePanel() {
        initComponents();
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        befreiungerlaubnisTable1 = new de.cismet.verdis.gui.befreiungerlaubnis.BefreiungerlaubnisTable();

        setLayout(new java.awt.BorderLayout());

        befreiungerlaubnisTable1.addMouseListener(new java.awt.event.MouseAdapter() {

                @Override
                public void mouseClicked(final java.awt.event.MouseEvent evt) {
                    befreiungerlaubnisTable1MouseClicked(evt);
                }
            });
        jScrollPane1.setViewportView(befreiungerlaubnisTable1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    } // </editor-fold>//GEN-END:initComponents

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void befreiungerlaubnisTable1MouseClicked(final java.awt.event.MouseEvent evt) { //GEN-FIRST:event_befreiungerlaubnisTable1MouseClicked
        if (CidsAppBackend.getInstance().isEditable() && (evt.getClickCount() == 2)) {
            if (!getTable().getSelectedBeans().isEmpty()) {
                final CidsBean cidsBean = getTable().getSelectedBeans().iterator().next();

                final JDialog dialog = new NewBefreiungerlaubnisDialog(StaticSwingTools.getParentFrame(this), cidsBean);
                dialog.addWindowListener(new WindowAdapter() {

                        @Override
                        public void windowClosed(final WindowEvent e) {
                            ((BefreiungerlaubnisTableModel)getTable().getModel()).fireTableDataChanged();
                        }
                    });
                StaticSwingTools.showDialog(dialog);
            }
        }
    } //GEN-LAST:event_befreiungerlaubnisTable1MouseClicked

    @Override
    public AbstractCidsBeanTable getTable() {
        return befreiungerlaubnisTable1;
    }
}
