/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.cismet.verdis.gui.aenderungsanfrage;

import Sirius.navigator.connection.SessionManager;

import javafx.application.Platform;

import javafx.concurrent.Worker;

import netscape.javascript.JSObject;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.event.KeyEvent;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;

import de.cismet.cids.custom.clientutils.ByteArrayActionDownload;

import de.cismet.cids.dynamics.CidsBean;

import de.cismet.connectioncontext.ConnectionContext;

import de.cismet.tools.BrowserLauncher;

import de.cismet.tools.gui.FXWebViewPanel;
import de.cismet.tools.gui.downloadmanager.Download;
import de.cismet.tools.gui.downloadmanager.DownloadManager;
import de.cismet.tools.gui.downloadmanager.DownloadManagerDialog;

import de.cismet.verdis.CidsAppBackend;
import de.cismet.verdis.EditModeListener;

import de.cismet.verdis.commons.constants.VerdisConstants;

import de.cismet.verdis.server.action.DownloadChangeRequestAnhangServerAction;
import de.cismet.verdis.server.json.AenderungsanfrageJson;
import de.cismet.verdis.server.json.NachrichtJson;
import de.cismet.verdis.server.json.NachrichtParameterJson;
import de.cismet.verdis.server.json.NachrichtParameterNotifyJson;
import de.cismet.verdis.server.json.NachrichtSachberarbeiterJson;
import de.cismet.verdis.server.json.NachrichtSystemJson;
import de.cismet.verdis.server.utils.AenderungsanfrageUtils;

/**
 * DOCUMENT ME!
 *
 * @author   jruiz
 * @version  $Revision$, $Date$
 */
public class AenderungsanfrageNachrichtenPanel extends javax.swing.JPanel implements EditModeListener,
    AenderungsanfrageHandler.ChangeListener {

    //~ Static fields/initializers ---------------------------------------------

    private static final transient org.apache.log4j.Logger LOG = org.apache.log4j.Logger.getLogger(
            AenderungsanfrageNachrichtenPanel.class);

    //~ Instance fields --------------------------------------------------------

    final FXWebViewPanel fxWebView = new FXWebViewPanel();

    private String email;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToggleButton jToggleButton1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates a new AenderungsanfrageNachrichtenPanel object.
     */
    public AenderungsanfrageNachrichtenPanel() {
        initComponents();

        jPanel1.add(fxWebView, BorderLayout.CENTER);

        AenderungsanfrageHandler.getInstance().addChangeListener(this);
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jButton6 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0),
                new java.awt.Dimension(0, 0),
                new java.awt.Dimension(32767, 0));
        jToggleButton1 = new javax.swing.JToggleButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0),
                new java.awt.Dimension(0, 0),
                new java.awt.Dimension(32767, 0));
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        org.openide.awt.Mnemonics.setLocalizedText(
            jButton6,
            org.openide.util.NbBundle.getMessage(
                AenderungsanfrageNachrichtenPanel.class,
                "AenderungsanfrageNachrichtenPanel.jButton6.text")); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {

                @Override
                public void actionPerformed(final java.awt.event.ActionEvent evt) {
                    jButton6ActionPerformed(evt);
                }
            });

        setLayout(new java.awt.GridBagLayout());

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/cismet/verdis/res/reload.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(
            jButton4,
            org.openide.util.NbBundle.getMessage(
                AenderungsanfrageNachrichtenPanel.class,
                "AenderungsanfrageNachrichtenPanel.jButton4.text"));                                             // NOI18N
        jButton4.setToolTipText(org.openide.util.NbBundle.getMessage(
                AenderungsanfrageNachrichtenPanel.class,
                "AenderungsanfrageNachrichtenPanel.jButton4.toolTipText"));                                      // NOI18N
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setFocusPainted(false);
        jButton4.setMaximumSize(new java.awt.Dimension(24, 24));
        jButton4.setMinimumSize(new java.awt.Dimension(24, 24));
        jButton4.setPreferredSize(new java.awt.Dimension(24, 24));
        jButton4.addActionListener(new java.awt.event.ActionListener() {

                @Override
                public void actionPerformed(final java.awt.event.ActionEvent evt) {
                    jButton4ActionPerformed(evt);
                }
            });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 3);
        jPanel3.add(jButton4, gridBagConstraints);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/cismet/verdis/res/read.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(
            jButton5,
            org.openide.util.NbBundle.getMessage(
                AenderungsanfrageNachrichtenPanel.class,
                "AenderungsanfrageNachrichtenPanel.jButton5.text"));                                           // NOI18N
        jButton5.setToolTipText(org.openide.util.NbBundle.getMessage(
                AenderungsanfrageNachrichtenPanel.class,
                "AenderungsanfrageNachrichtenPanel.jButton5.toolTipText"));                                    // NOI18N
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setEnabled(false);
        jButton5.setFocusPainted(false);
        jButton5.setMaximumSize(new java.awt.Dimension(24, 24));
        jButton5.setMinimumSize(new java.awt.Dimension(24, 24));
        jButton5.setPreferredSize(new java.awt.Dimension(24, 24));
        jButton5.addActionListener(new java.awt.event.ActionListener() {

                @Override
                public void actionPerformed(final java.awt.event.ActionEvent evt) {
                    jButton5ActionPerformed(evt);
                }
            });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 3);
        jPanel3.add(jButton5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        jPanel3.add(filler3, gridBagConstraints);

        jToggleButton1.setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/de/cismet/verdis/res/hide_system_messages.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(
            jToggleButton1,
            org.openide.util.NbBundle.getMessage(
                AenderungsanfrageNachrichtenPanel.class,
                "AenderungsanfrageNachrichtenPanel.jToggleButton1.text"));                  // NOI18N
        jToggleButton1.setToolTipText(org.openide.util.NbBundle.getMessage(
                AenderungsanfrageNachrichtenPanel.class,
                "AenderungsanfrageNachrichtenPanel.jToggleButton1.toolTipText"));           // NOI18N
        jToggleButton1.setBorderPainted(false);
        jToggleButton1.setContentAreaFilled(false);
        jToggleButton1.setFocusPainted(false);
        jToggleButton1.setMaximumSize(new java.awt.Dimension(24, 24));
        jToggleButton1.setMinimumSize(new java.awt.Dimension(24, 24));
        jToggleButton1.setPreferredSize(new java.awt.Dimension(24, 24));
        jToggleButton1.setSelectedIcon(new javax.swing.ImageIcon(
                getClass().getResource("/de/cismet/verdis/res/show_system_messages.png"))); // NOI18N
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {

                @Override
                public void actionPerformed(final java.awt.event.ActionEvent evt) {
                    jToggleButton1ActionPerformed(evt);
                }
            });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 0);
        jPanel3.add(jToggleButton1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        jPanel3.add(filler4, gridBagConstraints);

        jButton3.setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/de/cismet/verdis/res/download_comments.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(
            jButton3,
            org.openide.util.NbBundle.getMessage(
                AenderungsanfrageNachrichtenPanel.class,
                "AenderungsanfrageNachrichtenPanel.jButton3.text"));                     // NOI18N
        jButton3.setToolTipText(org.openide.util.NbBundle.getMessage(
                AenderungsanfrageNachrichtenPanel.class,
                "AenderungsanfrageNachrichtenPanel.jButton3.toolTipText"));              // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setFocusPainted(false);
        jButton3.setMaximumSize(new java.awt.Dimension(24, 24));
        jButton3.setMinimumSize(new java.awt.Dimension(24, 24));
        jButton3.setPreferredSize(new java.awt.Dimension(24, 24));
        jButton3.addActionListener(new java.awt.event.ActionListener() {

                @Override
                public void actionPerformed(final java.awt.event.ActionEvent evt) {
                    jButton3ActionPerformed(evt);
                }
            });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 3);
        jPanel3.add(jButton3, gridBagConstraints);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/cismet/verdis/res/send_mail.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(
            jButton2,
            org.openide.util.NbBundle.getMessage(
                AenderungsanfrageNachrichtenPanel.class,
                "AenderungsanfrageNachrichtenPanel.jButton2.text"));                                                // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setFocusPainted(false);
        jButton2.setMaximumSize(new java.awt.Dimension(24, 24));
        jButton2.setMinimumSize(new java.awt.Dimension(24, 24));
        jButton2.setPreferredSize(new java.awt.Dimension(24, 24));

        final org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(
                org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE,
                this,
                org.jdesktop.beansbinding.ELProperty.create("${email}"),
                jButton2,
                org.jdesktop.beansbinding.BeanProperty.create("toolTipText"));
        bindingGroup.addBinding(binding);

        jButton2.addActionListener(new java.awt.event.ActionListener() {

                @Override
                public void actionPerformed(final java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
                }
            });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 3);
        jPanel3.add(jButton2, gridBagConstraints);
        jButton2.setVisible(false);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        add(jPanel3, gridBagConstraints);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        add(jPanel1, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jScrollPane2.setMinimumSize(new java.awt.Dimension(19, 82));

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(3);
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {

                @Override
                public void keyPressed(final java.awt.event.KeyEvent evt) {
                    jTextArea1KeyPressed(evt);
                }
            });
        jScrollPane2.setViewportView(jTextArea1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        jPanel2.add(jScrollPane2, gridBagConstraints);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/cismet/verdis/res/send_message.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(
            jButton1,
            org.openide.util.NbBundle.getMessage(
                AenderungsanfrageNachrichtenPanel.class,
                "AenderungsanfrageNachrichtenPanel.jButton1.text"));                                                   // NOI18N
        jButton1.setToolTipText(org.openide.util.NbBundle.getMessage(
                AenderungsanfrageNachrichtenPanel.class,
                "AenderungsanfrageNachrichtenPanel.jButton1.toolTipText"));                                            // NOI18N
        jButton1.setMaximumSize(new java.awt.Dimension(48, 48));
        jButton1.setMinimumSize(new java.awt.Dimension(48, 48));
        jButton1.setPreferredSize(new java.awt.Dimension(48, 48));
        jButton1.addActionListener(new java.awt.event.ActionListener() {

                @Override
                public void actionPerformed(final java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel2.add(jButton1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        add(jPanel2, gridBagConstraints);

        bindingGroup.bind();
    } // </editor-fold>//GEN-END:initComponents

    /**
     * DOCUMENT ME!
     */
    private void sendMessagePressed() {
        final String text = jTextArea1.getText().trim();
        if ((jTextArea1.getText() != null) && !jTextArea1.getText().trim().isEmpty()) {
            final AenderungsanfrageJson aenderungsanfrage = getAenderungsanfrage();

            // Nachricht erzeugen und lokal hinzufügen
            final NachrichtJson nachrichtJson = new NachrichtSachberarbeiterJson(
                    null,
                    null,
                    null,
                    text,
                    SessionManager.getSession().getUser().getName(),
                    true);
            aenderungsanfrage.getNachrichten().add(nachrichtJson);

            // GUI vorab schonmal anpassen
            refresh(aenderungsanfrage);
            jTextArea1.setText("");
        }
    }

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void jButton1ActionPerformed(final java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton1ActionPerformed
        sendMessagePressed();
    }                                                                            //GEN-LAST:event_jButton1ActionPerformed

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */

    public String getEmail() {
        return email;
    }

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void jToggleButton1ActionPerformed(final java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jToggleButton1ActionPerformed
        refresh();
        jToggleButton1.setToolTipText(jToggleButton1.isSelected() ? "Systemnachrichten verbergen"
                                                                  : "Systemnachrichten anzeigen");
    }                                                                                  //GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void jButton2ActionPerformed(final java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton2ActionPerformed
        try {
            BrowserLauncher.openURL("mailto:" + email);
        } catch (final Exception ex) {
            LOG.error(ex, ex);
        }
    }                                                                            //GEN-LAST:event_jButton2ActionPerformed

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void jButton3ActionPerformed(final java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton3ActionPerformed
        final AenderungsanfrageJson aenderungsanfrage = getAenderungsanfrage();

        if ((aenderungsanfrage != null) && (aenderungsanfrage.getNachrichten() != null)) {
            final String jobname;
            if (DownloadManagerDialog.getInstance().showAskingForUserTitleDialog(this)) {
                jobname = DownloadManagerDialog.getInstance().getJobName();
            } else {
                jobname = null;
            }

            DownloadManager.instance()
                    .add(new AenderungsanfrageDownload(
                            jobname,
                            aenderungsanfrage,
                            ConnectionContext.createDeprecated()));
        }
    } //GEN-LAST:event_jButton3ActionPerformed

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void jTextArea1KeyPressed(final java.awt.event.KeyEvent evt) { //GEN-FIRST:event_jTextArea1KeyPressed
        if (KeyEvent.VK_UP == evt.getKeyCode()) {
            redoLastMessage();
        } else if ((KeyEvent.VK_ENTER == evt.getKeyCode()) && (evt.isControlDown() || evt.isAltDown())) {
            sendMessagePressed();
        }
    }                                                                      //GEN-LAST:event_jTextArea1KeyPressed

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void jButton4ActionPerformed(final java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton4ActionPerformed
        jButton1.setEnabled(false);
        new SwingWorker<Void, Void>() {

                @Override
                protected Void doInBackground() throws Exception {
                    AenderungsanfrageHandler.getInstance().reloadCurrentAnfrage();
                    return null;
                }

                @Override
                protected void done() {
                    jButton1.setEnabled(true);
                }
            }.execute();
    } //GEN-LAST:event_jButton4ActionPerformed

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void jButton5ActionPerformed(final java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton5ActionPerformed
        new SwingWorker<Void, Void>() {

                @Override
                protected Void doInBackground() throws Exception {
                    AenderungsanfrageHandler.getInstance()
                            .sendAenderungsanfrage(AenderungsanfrageHandler.getInstance().getAenderungsanfrage());
                    return null;
                }

                @Override
                protected void done() {
                    try {
                        get();
                        jButton5.setEnabled(false);
                        AenderungsanfrageHandler.getInstance().reloadAenderungsanfrageBeans();
                    } catch (final Exception ex) {
                        LOG.error(ex, ex);
                    }
                }
            }.execute();
    } //GEN-LAST:event_jButton5ActionPerformed

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void jButton6ActionPerformed(final java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton6ActionPerformed
        final AenderungsanfrageJson aenderungsanfrage = getAenderungsanfrage();

        final NachrichtJson nachrichtJson = new NachrichtSystemJson(
                null,
                null,
                null,
                new NachrichtParameterNotifyJson(false),
                SessionManager.getSession().getUser().getName());
        aenderungsanfrage.getNachrichten().add(nachrichtJson);
        refresh(aenderungsanfrage);
        jPanel1.remove(jButton6);

        // nachricht tatsächlich senden
        new SwingWorker<Void, Void>() {

                @Override
                protected Void doInBackground() throws Exception {
                    try {
                        AenderungsanfrageHandler.getInstance()
                                .sendAenderungsanfrage(new AenderungsanfrageJson(
                                        aenderungsanfrage.getKassenzeichen(),
                                        aenderungsanfrage.getEmailAdresse(),
                                        aenderungsanfrage.getEmailVerifiziert(),
                                        null,
                                        null,
                                        aenderungsanfrage.getNachrichten()));
                    } catch (final Exception ex) {
                        LOG.error(ex, ex);
                    }
                    return null;
                }
            }.execute();
    } //GEN-LAST:event_jButton6ActionPerformed

    /**
     * DOCUMENT ME!
     */
    private void redoLastMessage() {
        final AenderungsanfrageJson aenderungsanfrage = getAenderungsanfrage();
        if ((aenderungsanfrage != null)
                    && (aenderungsanfrage.getNachrichten() != null)
                    && !aenderungsanfrage.getNachrichten().isEmpty()) {
            final List<NachrichtJson> reversedNachrichten = new ArrayList<>(aenderungsanfrage.getNachrichten());
            Collections.reverse(reversedNachrichten);

            for (final NachrichtJson lastNachricht : reversedNachrichten) {
                if (NachrichtJson.Typ.CLERK.equals(lastNachricht.getTyp())
                            && Boolean.TRUE.equals(lastNachricht.getDraft())) {
                    aenderungsanfrage.getNachrichten().remove(lastNachricht);
                    refresh(aenderungsanfrage);
                    jTextArea1.setText(lastNachricht.getNachricht() + "\n");
                    break;
                }
            }
        }
    }

    /**
     * DOCUMENT ME!
     */
    private void refresh() {
        refresh(true);
    }

    /**
     * DOCUMENT ME!
     *
     * @param  scrollToBottom  DOCUMENT ME!
     */
    private void refresh(final boolean scrollToBottom) {
        refresh(getAenderungsanfrage(), scrollToBottom);
    }

    /**
     * DOCUMENT ME!
     *
     * @param  aenderungsanfrage  DOCUMENT ME!
     */
    private void refresh(final AenderungsanfrageJson aenderungsanfrage) {
        refresh(aenderungsanfrage, true);
    }

    /**
     * DOCUMENT ME!
     *
     * @param  aenderungsanfrage  DOCUMENT ME!
     * @param  scrollToBottom     DOCUMENT ME!
     */
    private void refresh(final AenderungsanfrageJson aenderungsanfrage, final boolean scrollToBottom) {
        if (!SwingUtilities.isEventDispatchThread()) {
            SwingUtilities.invokeLater(new Runnable() {

                    @Override
                    public void run() {
                        refresh(aenderungsanfrage);
                    }
                });
        } else {
            final List<NachrichtJson> nachrichten = (aenderungsanfrage != null) ? aenderungsanfrage.getNachrichten()
                                                                                : null;

            jPanel1.remove(jButton6);
            try {
                fxWebView.loadContent(AenderungsanfrageUtils.createChatHtmlFromAenderungsanfrage(
                        aenderungsanfrage,
                        12,
                        jToggleButton1.isSelected(),
                        false,
                        false));

                new SwingWorker<Void, Void>() {

                        @Override
                        protected Void doInBackground() throws Exception {
                            Worker.State state = null;
                            while ((state = fxWebView.getWebEngine().getLoadWorker().getState())
                                        != Worker.State.SUCCEEDED) {
                                if ((state == Worker.State.FAILED) || (state == Worker.State.CANCELLED)) {
                                    throw new Exception("worker failed or cancelled");
                                }
                                Thread.sleep(10);
                            }
                            return null;
                        }

                        @Override
                        protected void done() {
                            Platform.runLater(new Runnable() {

                                    @Override
                                    public void run() {
                                        ((JSObject)fxWebView.getWebEngine().executeScript("window")).setMember(
                                            "java",
                                            AenderungsanfrageNachrichtenPanel.this);
                                        fxWebView.getWebEngine()
                                                .executeScript("window.scrollTo(0, document.body.scrollHeight);");
                                    }
                                });
                        }
                    }.execute();
            } catch (final Exception ex) {
                LOG.error(ex, ex);
            }

            if (nachrichten != null) {
                NachrichtJson lastNachrichtJson = null;
                for (final NachrichtJson nachrichtJson : nachrichten) {
                    if (NachrichtJson.Typ.CITIZEN.equals(nachrichtJson.getTyp())
                                && Boolean.TRUE.equals(nachrichtJson.getDraft())) {
                        continue;
                    }
                    if (NachrichtJson.Typ.SYSTEM.equals(nachrichtJson.getTyp())
                                && !jToggleButton1.isSelected()) {
                        continue;
                    }
                    lastNachrichtJson = nachrichtJson;
                }
                if ((lastNachrichtJson != null) && !CidsAppBackend.getInstance().isEditable()) {    // to ensure that all we don't send notifications before changes are undrafted
                    final boolean lastMessageIsNotification =
                        NachrichtJson.Typ.SYSTEM.equals(lastNachrichtJson.getTyp())
                                && (lastNachrichtJson.getNachrichtenParameter() != null)
                                && NachrichtParameterJson.Type.NOTIFY.equals(
                                    lastNachrichtJson.getNachrichtenParameter().getType());
                    final boolean lastMessageIsStatusDone = (lastNachrichtJson.getNachrichtenParameter() != null)
                                && AenderungsanfrageUtils.Status.NONE.equals(lastNachrichtJson.getNachrichtenParameter()
                                    .getStatus());
                    final boolean lastMessageWasFromMe = SessionManager.getSession()
                                .getUser()
                                .getName()
                                .equals(lastNachrichtJson.getAbsender());
                    final boolean hasVerifiedEmail = (aenderungsanfrage.getEmailAdresse() != null)
                                && Boolean.TRUE.equals(aenderungsanfrage.getEmailVerifiziert());
                    final boolean showButton = hasVerifiedEmail
                                && lastMessageWasFromMe
                                && !lastMessageIsNotification
                                && !lastMessageIsStatusDone;
                    if (showButton) {
                        final java.awt.GridBagConstraints gridBagConstraints = new java.awt.GridBagConstraints();
                        gridBagConstraints.gridx = 0;
                        gridBagConstraints.gridy = GridBagConstraints.RELATIVE;
                        gridBagConstraints.fill = java.awt.GridBagConstraints.NONE;
                        gridBagConstraints.weightx = 1.0;
                        gridBagConstraints.insets = new java.awt.Insets(0, 20, 20, 20);
                        jPanel1.add(jButton6, BorderLayout.SOUTH);
                    }
                }
            }

            jPanel1.doLayout();
            revalidate();
        }
    }

    /**
     * DOCUMENT ME!
     *
     * @param  name  DOCUMENT ME!
     * @param  json  DOCUMENT ME!
     */
    public void linkClicked(final String name, final String json) {
        try {
            if (DownloadManagerDialog.getInstance().showAskingForUserTitleDialog(this)) {
                final String jobname = DownloadManagerDialog.getInstance().getJobName();
                final String filename = name;
                final Download download = new ByteArrayActionDownload(
                        VerdisConstants.DOMAIN,
                        DownloadChangeRequestAnhangServerAction.TASK_NAME,
                        json,
                        null,
                        filename,
                        jobname,
                        filename.substring(0, filename.lastIndexOf(".")),
                        filename.substring(filename.lastIndexOf(".")),
                        ConnectionContext.createDeprecated());

                DownloadManager.instance().add(download);
            }
        } catch (final Exception ex) {
            LOG.error(ex, ex);
        }
    }

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    public AenderungsanfrageJson getAenderungsanfrage() {
        return AenderungsanfrageHandler.getInstance().getAenderungsanfrage();
    }

    @Override
    public void editModeChanged() {
        setEnabled(CidsAppBackend.getInstance().isEditable()
                    && (AenderungsanfrageHandler.getInstance().getAenderungsanfrage() != null));
    }

    @Override
    public void setEnabled(final boolean enabled) {
        super.setEnabled(enabled);
        jPanel2.setVisible(enabled);
        refresh();
    }

    @Override
    public void aenderungsanfrageChanged(final AenderungsanfrageJson aenderungsanfrage) {
        refresh(aenderungsanfrage);
        final boolean isNewCitizenMessage = (AenderungsanfrageHandler.getInstance().getCidsBean() != null)
                    && AenderungsanfrageUtils.Status.NEW_CITIZEN_MESSAGE.toString()
                    .equals((String)AenderungsanfrageHandler.getInstance().getCidsBean().getProperty(
                                "status.schluessel"));
        jButton5.setEnabled(!isEnabled() && isNewCitizenMessage);
    }

    @Override
    public void aenderungsanfrageBeansChanged(final List<CidsBean> aenderungsanfrageBeans) {
    }

    @Override
    public void loadingStarted() {
    }

    @Override
    public void loadingFinished() {
    }

    //~ Inner Classes ----------------------------------------------------------

    /**
     * DOCUMENT ME!
     *
     * @version  $Revision$, $Date$
     */
    public static class myPanel extends JPanel {

        //~ Methods ------------------------------------------------------------

        @Override
        public void setPreferredSize(final Dimension preferredSize) {
            super.setPreferredSize(preferredSize); // To change body of generated methods, choose Tools | Templates.
        }
    }
}
