/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.cismet.verdis.gui.aenderungsanfrage;

import com.jgoodies.looks.plastic.Plastic3DLookAndFeel;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;

import javax.swing.JDialog;

import de.cismet.tools.gui.StaticSwingTools;

import de.cismet.verdis.server.utils.aenderungsanfrage.AnfrageJson;
import de.cismet.verdis.server.utils.aenderungsanfrage.FlaecheAnschlussgradJson;
import de.cismet.verdis.server.utils.aenderungsanfrage.FlaecheFlaechenartJson;
import de.cismet.verdis.server.utils.aenderungsanfrage.FlaecheGroesseJson;
import de.cismet.verdis.server.utils.aenderungsanfrage.FlaecheJson;
import de.cismet.verdis.server.utils.aenderungsanfrage.FlaechePruefungJson;
import de.cismet.verdis.server.utils.aenderungsanfrage.NachrichtAnhangJson;
import de.cismet.verdis.server.utils.aenderungsanfrage.NachrichtJson;
import de.cismet.verdis.server.utils.aenderungsanfrage.PruefungJson;

/**
 * DOCUMENT ME!
 *
 * @author   jruiz
 * @version  $Revision$, $Date$
 */
public class AenderungsanfrageNachrichtDialog extends javax.swing.JDialog {

    //~ Instance fields --------------------------------------------------------

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private de.cismet.verdis.gui.aenderungsanfrage.AenderungsanfrageNachrichtenPanel aenderungsanfrageNachrichtenPanel1;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form NewJDialog.
     *
     * @param  parent  DOCUMENT ME!
     * @param  modal   DOCUMENT ME!
     */
    public AenderungsanfrageNachrichtDialog(final java.awt.Frame parent, final boolean modal) {
        super(parent, modal);
        initComponents();
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        final java.awt.GridBagConstraints gridBagConstraints;

        aenderungsanfrageNachrichtenPanel1 =
            new de.cismet.verdis.gui.aenderungsanfrage.AenderungsanfrageNachrichtenPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(aenderungsanfrageNachrichtenPanel1, gridBagConstraints);

        pack();
    } // </editor-fold>//GEN-END:initComponents

    /**
     * DOCUMENT ME!
     *
     * @param  args  the command line arguments
     */
    public static void main(final String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            javax.swing.UIManager.setLookAndFeel(new Plastic3DLookAndFeel());
        } catch (final Exception ex) {
            java.util.logging.Logger.getLogger(AenderungsanfrageNachrichtDialog.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

                @Override
                public void run() {
                    final AenderungsanfrageNachrichtDialog dialog = new AenderungsanfrageNachrichtDialog(
                            new javax.swing.JFrame(),
                            true);
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                            @Override
                            public void windowClosing(final java.awt.event.WindowEvent e) {
                                System.exit(0);
                            }
                        });

                    final AnfrageJson anfrageJson = dialog.getComplexAnfrageJson();
                    dialog.aenderungsanfrageNachrichtenPanel1.setNachrichten(anfrageJson.getNachrichten());
                    dialog.setVisible(true);
                }
            });
    }

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    private AnfrageJson getSimpleAnfrageJson() {
        final Map<String, FlaecheJson> flaechen = new HashMap<>();
        flaechen.put("5", new FlaecheGroesseJson(12));
        final AnfrageJson anfrageJson = new AnfrageJson(
                60004629,
                flaechen,
                new ArrayList<>(
                    Arrays.asList(
                        new NachrichtJson(
                            NachrichtJson.Typ.CITIZEN,
                            new Date(47110815),
                            "Da passt was nicht weil isso, siehe lustiges pdf !",
                            "Bürger",
                            new NachrichtAnhangJson("lustiges.pdf", "aaa-bbb-ccc")))));
        return anfrageJson;
    }

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    private AnfrageJson getComplexAnfrageJson() {
        final AnfrageJson anfrageJson = getSimpleAnfrageJson();
        anfrageJson.getNachrichten()
                .add(new NachrichtJson(
                        NachrichtJson.Typ.CLERK,
                        new Date(47110815),
                        "Konnte nichts feststellen, alles in Ordnung.",
                        "Dirk Steinbacher"));
        anfrageJson.getNachrichten().add(new NachrichtJson(
                new Date(47110815),
                "REJECT_GROESSE(5, 12)"));
        anfrageJson.getNachrichten()
                .add(new NachrichtJson(
                        NachrichtJson.Typ.CITIZEN,
                        new Date(47110815),
                        "Oh, falsches PDF, siehe richtiges pdf.",
                        "Bürger",
                        new NachrichtAnhangJson("richtiges.pdf", "ddd-eee-fff")));
        anfrageJson.getNachrichten()
                .add(new NachrichtJson(
                        NachrichtJson.Typ.CLERK,
                        new Date(47110815),
                        "Ach so, verstehe. Alles Klar !",
                        "Dirk Steinbacher"));
        anfrageJson.getNachrichten().add(new NachrichtJson(
                new Date(47110815),
                "ACCEPT_GROESSE(5, 12)"));
        anfrageJson.getNachrichten()
                .add(new NachrichtJson(NachrichtJson.Typ.CITIZEN,
                        new Date(47110815),
                        "Geht doch, danke.", "Bürger"));

        anfrageJson.getFlaechen().get("5").setFlaechenart(new FlaecheFlaechenartJson("Gründach", "GDF"));
        anfrageJson.getFlaechen().get("5").setAnschlussgrad(new FlaecheAnschlussgradJson("versickernd", "vers."));
        anfrageJson.getFlaechen()
                .get("5")
                .setPruefung(new FlaechePruefungJson(
                        new PruefungJson(PruefungJson.Status.ACCEPTED, "test", new Date(47110815)),
                        new PruefungJson(PruefungJson.Status.REJECTED, "test", new Date(47110815)),
                        new PruefungJson(PruefungJson.Status.NONE, "test", new Date(47110815))));

        return anfrageJson;
    }
}
