/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.cismet.verdis.gui.aenderungsanfrage;

import Sirius.navigator.connection.SessionManager;
import Sirius.navigator.exception.ConnectionException;

import Sirius.server.middleware.types.MetaObject;
import Sirius.server.middleware.types.MetaObjectNode;

import java.awt.event.KeyEvent;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

import javax.swing.JFrame;
import javax.swing.KeyStroke;

import de.cismet.cids.client.tools.DevelopmentTools;

import de.cismet.cids.dynamics.CidsBean;

import de.cismet.connectioncontext.AbstractConnectionContext;
import de.cismet.connectioncontext.ConnectionContext;

import de.cismet.tools.gui.StaticSwingTools;
import de.cismet.tools.gui.log4jquickconfig.Log4JQuickConfig;

import de.cismet.verdis.commons.constants.VerdisConstants;

import de.cismet.verdis.server.search.AenderungsanfrageSearchStatement;

/**
 * DOCUMENT ME!
 *
 * @author   jruiz
 * @version  $Revision$, $Date$
 */
public class AenderungsanfrageDialog extends javax.swing.JDialog {

    //~ Static fields/initializers ---------------------------------------------

    private static final org.apache.log4j.Logger LOG = org.apache.log4j.Logger.getLogger(
            AenderungsanfrageDialog.class);

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private de.cismet.verdis.gui.aenderungsanfrage.AenderungsanfrageTablePanel aenderungsanfrageTablePanel1;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCancel1;
    private javax.swing.JButton btnCancel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates a new BEDialog object.
     */
    public AenderungsanfrageDialog() {
        super((JFrame)null, false);
        initComponents();

        getRootPane().setDefaultButton(btnCancel);
//        StaticSwingTools.doClickButtonOnKeyStroke(btnGo, KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), getRootPane());
        StaticSwingTools.doClickButtonOnKeyStroke(
            btnCancel,
            KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0),
            getRootPane());
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    public AenderungsanfrageTablePanel getAenderungsanfrageTablePanel() {
        return aenderungsanfrageTablePanel1;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnCancel2 = new javax.swing.JButton();
        btnCancel1 = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        aenderungsanfrageTablePanel1 = new de.cismet.verdis.gui.aenderungsanfrage.AenderungsanfrageTablePanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(AenderungsanfrageDialog.class, "AenderungsanfrageDialog.title")); // NOI18N
        setModal(true);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        btnCancel2.setText(org.openide.util.NbBundle.getMessage(
                AenderungsanfrageDialog.class,
                "AenderungsanfrageDialog.btnCancel2.text")); // NOI18N
        btnCancel2.addActionListener(new java.awt.event.ActionListener() {

                @Override
                public void actionPerformed(final java.awt.event.ActionEvent evt) {
                    btnCancel2ActionPerformed(evt);
                }
            });
        jPanel2.add(btnCancel2);

        btnCancel1.setText(org.openide.util.NbBundle.getMessage(
                AenderungsanfrageDialog.class,
                "AenderungsanfrageDialog.btnCancel1.text")); // NOI18N
        btnCancel1.addActionListener(new java.awt.event.ActionListener() {

                @Override
                public void actionPerformed(final java.awt.event.ActionEvent evt) {
                    btnCancel1ActionPerformed(evt);
                }
            });
        jPanel2.add(btnCancel1);

        btnCancel.setText(org.openide.util.NbBundle.getMessage(
                AenderungsanfrageDialog.class,
                "AenderungsanfrageDialog.btnCancel.text")); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {

                @Override
                public void actionPerformed(final java.awt.event.ActionEvent evt) {
                    btnCancelActionPerformed(evt);
                }
            });
        jPanel2.add(btnCancel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(jPanel2, gridBagConstraints);

        jPanel4.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel4.add(aenderungsanfrageTablePanel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jPanel4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    } // </editor-fold>//GEN-END:initComponents

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void btnCancelActionPerformed(final java.awt.event.ActionEvent evt) { //GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }                                                                             //GEN-LAST:event_btnCancelActionPerformed

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void btnCancel1ActionPerformed(final java.awt.event.ActionEvent evt) { //GEN-FIRST:event_btnCancel1ActionPerformed
        // TODO add your handling code here:
    } //GEN-LAST:event_btnCancel1ActionPerformed

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void btnCancel2ActionPerformed(final java.awt.event.ActionEvent evt) { //GEN-FIRST:event_btnCancel2ActionPerformed
        // TODO add your handling code here:
    } //GEN-LAST:event_btnCancel2ActionPerformed

    /**
     * DOCUMENT ME!
     *
     * @param  cidsBeanList  DOCUMENT ME!
     */
    public void setCidsBeanList(final List<CidsBean> cidsBeanList) {
        getAenderungsanfrageTablePanel().getModel().setCidsBeans(cidsBeanList);
        getAenderungsanfrageTablePanel().repaint();
    }

    @Override
    public void dispose() {
        super.dispose();
    }

    /**
     * DOCUMENT ME!
     *
     * @param  args  DOCUMENT ME!
     */
    public static void main(final String[] args) {
        final ConnectionContext connectionContext = ConnectionContext.create(
                AbstractConnectionContext.Category.STATIC,
                "test");

        Log4JQuickConfig.configure4LumbermillOnLocalhost();
        DevelopmentTools.showSimpleLoginDialog(
            "http://localhost:9986/callserver/binary",
            VerdisConstants.DOMAIN,
            true,
            connectionContext);

        final AenderungsanfrageSearchStatement search = new AenderungsanfrageSearchStatement();

        final List<CidsBean> cidsBeanList = new ArrayList<>();
        try {
            final Collection<MetaObjectNode> mons = SessionManager.getProxy()
                        .customServerSearch(SessionManager.getSession().getUser(), search, connectionContext);
            for (final MetaObjectNode mon : mons) {
                final MetaObject mo = SessionManager.getProxy()
                            .getMetaObject(mon.getObjectId(),
                                mon.getClassId(),
                                VerdisConstants.DOMAIN,
                                connectionContext);
                cidsBeanList.add(mo.getBean());
            }
            LOG.error(cidsBeanList.size());
        } catch (final ConnectionException ex) {
            LOG.fatal(ex, ex);
        }

        final AenderungsanfrageDialog dialog = AenderungsanfrageDialog.getInstance();
        dialog.setCidsBeanList(cidsBeanList);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                @Override
                public void windowClosing(final java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });

        StaticSwingTools.showDialog(dialog);
    }

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    public static AenderungsanfrageDialog getInstance() {
        return LazyInitialiser.INSTANCE;
    }

    //~ Inner Classes ----------------------------------------------------------

    /**
     * DOCUMENT ME!
     *
     * @version  $Revision$, $Date$
     */
    private static final class LazyInitialiser {

        //~ Static fields/initializers -----------------------------------------

        private static final AenderungsanfrageDialog INSTANCE = new AenderungsanfrageDialog();

        //~ Constructors -------------------------------------------------------

        /**
         * Creates a new LazyInitialiser object.
         */
        private LazyInitialiser() {
        }
    }
}
