/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
/*
 * DocPanel.java
 *
 * Created on 16. Dezember 2004, 15:39
 */
package de.cismet.gui.tools;
import de.cismet.cids.dynamics.CidsBean;
import de.cismet.cids.dynamics.CidsBeanStore;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;


import java.util.Iterator;

import javax.swing.Icon;
import javax.swing.JOptionPane;



import de.cismet.verdis.gui.DokumentenPanel;
import java.util.ArrayList;
/**
 * Klasse zum Anzeigen von Links und zugehoerigen Icons in einer Anwendung.<br>
 * Bei Klick wird die URL im Webbrowser geoeffnet.
 *
 * @author   hell
 * @version  $Revision$, $Date$
 */
public class DocPanel extends javax.swing.JPanel implements CidsBeanStore{

    //~ Static fields/initializers ---------------------------------------------

    public static final int MAX_DESCRIPTION_LENGTH = 12;
    public static final String DELETE_ACTION_COMMAND = "DELETE_ACTION";

    //~ Instance fields --------------------------------------------------------

    ArrayList actionListeners = new ArrayList();
    private final org.apache.log4j.Logger log = org.apache.log4j.Logger.getLogger(this.getClass());
        private String desc;
    private String gotoUrl;
    private java.applet.AppletContext appletContext = null;
    private boolean deletable = false;
    private CidsBean dmsUrl;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDescr;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JMenuItem mniDelete;
    private javax.swing.JPopupMenu pmnLink;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form DocPanel.
     */
    public DocPanel() {
        initComponents();
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * Setzt den Appletkontext.<br>
     * Wird dann benoetigt falls DocPanel in einem Applett benutzt wird
     *
     * @param  appletContext  Appletkontext
     */
    public void setAplettContext(final java.applet.AppletContext appletContext) {
        this.appletContext = appletContext;
    }
    /**
     * Liefert das dargestellte Symbol zurueck.
     *
     * @return  Icon
     */
    public Icon getIcon() {
        return lblIcon.getIcon();
    }

    /**
     * Setzt das dargestellte Symbol.
     *
     * @param  icon  Dargestelltes Symbol
     */
    public void setIcon(final Icon icon) {
        lblIcon.setIcon(icon);
    }

    /**
     * Liefert die Beschreibung.
     *
     * @return  Beschreibung
     */
    public String getDesc() {
        return this.desc;
    }

    /**
     * Setzt die Beschreibung.
     *
     * @param  desc  Beschreibung
     */
    public void setDesc(final String desc) {
        this.desc = desc;
        if (desc.length() > MAX_DESCRIPTION_LENGTH) {
            this.lblDescr.setText(desc.substring(0, MAX_DESCRIPTION_LENGTH) + "...");
            this.lblDescr.setToolTipText(desc);
        } else {
            this.lblDescr.setText(desc);
        }
    }

    /**
     * Liefert die verknuepfte URL.
     *
     * @return  URL
     */
    public String getGotoUrl() {
        return gotoUrl;
    }

    /**
     * setzt die verknuepfte URL.
     *
     * @param  gotoUrl  URL
     */
    public void setGotoUrl(final String gotoUrl) {
        this.gotoUrl = gotoUrl;
        lblIcon.setToolTipText(gotoUrl);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pmnLink = new javax.swing.JPopupMenu();
        mniDelete = new javax.swing.JMenuItem();
        lblIcon = new javax.swing.JLabel();
        lblDescr = new javax.swing.JLabel();

        mniDelete.setText("Link entfernen");
        mniDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDeleteActionPerformed(evt);
            }
        });
        pmnLink.add(mniDelete);

        setMaximumSize(new java.awt.Dimension(100, 50));
        setMinimumSize(new java.awt.Dimension(100, 50));
        setPreferredSize(new java.awt.Dimension(100, 50));
        setLayout(new java.awt.BorderLayout());

        lblIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/cismet/verdis/res/images/filetypes/dms_default.png"))); // NOI18N
        lblIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblIconMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblIconMouseReleased(evt);
            }
        });
        add(lblIcon, java.awt.BorderLayout.CENTER);

        lblDescr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDescr.setText("Beschreibung");
        lblDescr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDescrMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDescrMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDescrMouseExited(evt);
            }
        });
        lblDescr.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblDescrMouseMoved(evt);
            }
        });
        add(lblDescr, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void lblIconMousePressed(final java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconMousePressed
        if ((evt.isPopupTrigger())) {
            popupTrigged(evt);
        }
    }//GEN-LAST:event_lblIconMousePressed

    private void popupTrigged(final java.awt.event.MouseEvent evt) {
        if (isDeletable()) {
            if (this.getParent().getParent() instanceof DokumentenPanel) {
                if (((DokumentenPanel)(getParent().getParent())).isInEditMode()) {
                    pmnLink.show(evt.getComponent(), evt.getX(), evt.getY());
                }
            }            
        }
    }
    
    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void mniDeleteActionPerformed(final java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDeleteActionPerformed
        fireDeleteActionPerformed();
    }//GEN-LAST:event_mniDeleteActionPerformed

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void lblDescrMouseClicked(final java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDescrMouseClicked

        if (gotoUrl == null) {
            JOptionPane.showMessageDialog(this, "Es wurde keine Url hinterlegt!", "Fehler", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            if (appletContext == null) {
                de.cismet.tools.BrowserLauncher.openURL(gotoUrl);
            } else {
                final java.net.URL u = new java.net.URL(gotoUrl);
                appletContext.showDocument(u, "cismetDocPanelFrame");
            }
        } catch (Exception e) {
            log.warn("Fehler beim Oeffnen von:" + gotoUrl + "\nNeuer Versuch", e);
            // Nochmal zur Sicherheit mit dem BrowserLauncher probieren
            try {
                de.cismet.tools.BrowserLauncher.openURL(gotoUrl);
            } catch (Exception e2) {
                log.warn("Auch das 2te Mal ging schief.Fehler beim Oeffnen von:" + gotoUrl + "\nLetzter Versuch", e2);
                try {
                    gotoUrl = gotoUrl.replaceAll("\\\\", "/");
                    gotoUrl = gotoUrl.replaceAll(" ", "%20");
                    de.cismet.tools.BrowserLauncher.openURL("file:///" + gotoUrl);
                } catch (Exception e3) {
                    log.error("Auch das 3te Mal ging schief.Fehler beim Oeffnen von:file://" + gotoUrl, e3);
                }
            }
        }
    }//GEN-LAST:event_lblDescrMouseClicked

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void lblDescrMouseExited(final java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDescrMouseExited
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblDescr.setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_lblDescrMouseExited

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void lblDescrMouseEntered(final java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDescrMouseEntered
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblDescr.setForeground(java.awt.Color.BLUE);
    }//GEN-LAST:event_lblDescrMouseEntered

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void lblDescrMouseMoved(final java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDescrMouseMoved
    }//GEN-LAST:event_lblDescrMouseMoved

    private void lblIconMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconMouseReleased
        if ((evt.isPopupTrigger())) {
            popupTrigged(evt);
        }
    }//GEN-LAST:event_lblIconMouseReleased

    /**
     * DOCUMENT ME!
     *
     * @param  al  DOCUMENT ME!
     */
    public void addActionListener(final ActionListener al) {
        actionListeners.add(al);
    }

    /**
     * DOCUMENT ME!
     *
     * @param  al  DOCUMENT ME!
     */
    public void removeActionListener(final ActionListener al) {
        actionListeners.remove(al);
    }
    /**
     * DOCUMENT ME!
     */
    public void fireDeleteActionPerformed() {
        final Iterator it = actionListeners.iterator();
        final ActionEvent event = new ActionEvent(this, 0, DELETE_ACTION_COMMAND);
        while (it.hasNext()) {
            final Object elem = (Object)it.next();
            if (elem instanceof ActionListener) {
                ((ActionListener)elem).actionPerformed(event);
            }
        }
    }

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    public boolean isDeletable() {
        return deletable;
    }

    /**
     * DOCUMENT ME!
     *
     * @param  deletable  DOCUMENT ME!
     */
    public void setDeletable(final boolean deletable) {
        this.deletable = deletable;
    }

    @Override
    public CidsBean getCidsBean() {
        return dmsUrl;
    }

    @Override
    public void setCidsBean(CidsBean cidsBean) {
        dmsUrl=cidsBean;
    }
}
